# Dredd configuration to validate API Contract based on OpenAPI/Swagger
dry-run: null
hookfiles: null
language: nodejs
server: cd backend && cargo run
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: backend/openapi.yaml # Reference to the swagger file
endpoint: 'http://localhost:5172' # Orbit Axum API URL
